/* Javascript output generated by archetype 1.3.2 */

/* Utils functions */

export const mk_int    = v  => {return { "int" : v.toString() }}
export const mk_string = v  => {return { "string" : v }}
export const mk_bytes  = v  => {return { "bytes" : v.toString() }}
export const mk_some   = v  => {return { "prim": "Some", "args": [ v ] }}
export const mk_none   = () => {return { "prim": "None" }}
export const mk_rational = (n, d) => {return {  "prim": "Pair", "args": [ {  "int": n.toString()  }, {  "int": d.toString()  } ] }}

/* Code */

export const code =
  [  {  "prim": "storage",
        "args": [
          {  "prim": "big_map",
             "args": [
               {  "prim": "address"  },
               {  "prim": "pair",
                  "args": [
                    {  "prim": "nat",
                       "annots": [
                         "%tokens"
                       ]
                    },
                    {  "prim": "map",
                       "args": [
                         {  "prim": "address"  },
                         {  "prim": "nat"  }
                       ]
                       ,
                       "annots": [
                         "%allowance"
                       ]
                    }
                  ]
               }
             ]
          }
        ]
  },
  {  "prim": "parameter",
     "args": [
       {  "prim": "or",
          "args": [
            {  "prim": "or",
               "args": [
                 {  "prim": "pair",
                    "args": [
                      {  "prim": "pair",
                         "args": [
                           {  "prim": "address",
                              "annots": [
                                "%owner"
                              ]
                           },
                           {  "prim": "address",
                              "annots": [
                                "%spender"
                              ]
                           }
                         ]
                      },
                      {  "prim": "contract",
                         "args": [
                           {  "prim": "nat"  }
                         ]
                         ,
                         "annots": [
                           "%callback"
                         ]
                      }
                    ]
                    ,
                    "annots": [
                      "%getAllowance"
                    ]
                 },
                 {  "prim": "pair",
                    "args": [
                      {  "prim": "address",
                         "annots": [
                           "%owner"
                         ]
                      },
                      {  "prim": "contract",
                         "args": [
                           {  "prim": "nat"  }
                         ]
                         ,
                         "annots": [
                           "%callback"
                         ]
                      }
                    ]
                    ,
                    "annots": [
                      "%getBalance"
                    ]
                 }
               ]
            },
            {  "prim": "or",
               "args": [
                 {  "prim": "pair",
                    "args": [
                      {  "prim": "address",
                         "annots": [
                           "%from"
                         ]
                      },
                      {  "prim": "pair",
                         "args": [
                           {  "prim": "address",
                              "annots": [
                                "%to"
                              ]
                           },
                           {  "prim": "nat",
                              "annots": [
                                "%value"
                              ]
                           }
                         ]
                      }
                    ]
                    ,
                    "annots": [
                      "%transfer"
                    ]
                 },
                 {  "prim": "pair",
                    "args": [
                      {  "prim": "address",
                         "annots": [
                           "%spender"
                         ]
                      },
                      {  "prim": "nat",
                         "annots": [
                           "%value"
                         ]
                      }
                    ]
                    ,
                    "annots": [
                      "%approve"
                    ]
                 }
               ]
            }
          ]
       }
     ]
  },
  {  "prim": "code",
     "args": [
       [  {  "prim": "NIL",
             "args": [
               {  "prim": "operation"  }
             ]
       },
       {  "prim": "DIG",
          "args": [
            {  "int": "1"  }
          ]
       },
       {  "prim": "UNPAIR"  },
       {  "prim": "IF_LEFT",
          "args": [
            [  {  "prim": "IF_LEFT",
                  "args": [
                    [  {  "prim": "UNPAIR"  },
                    {  "prim": "UNPAIR"  },
                    {  "prim": "SWAP"  },
                    {  "prim": "NIL",
                       "args": [
                         {  "prim": "operation"  }
                       ]
                    },
                    {  "prim": "NIL",
                       "args": [
                         {  "prim": "operation"  }
                       ]
                    },
                    {  "prim": "DUP",
                       "args": [
                         {  "int": "7"  }
                       ]
                    },
                    {  "prim": "ITER",
                       "args": [
                         [  {  "prim": "CONS"  }  ]
                       ]
                    },
                    {  "prim": "DUP",
                       "args": [
                         {  "int": "5"  }
                       ]
                    },
                    {  "prim": "AMOUNT"  },
                    {  "prim": "DUP",
                       "args": [
                         {  "int": "8"  }
                       ]
                    },
                    {  "prim": "DUP",
                       "args": [
                         {  "int": "7"  }
                       ]
                    },
                    {  "prim": "GET"  },
                    {  "prim": "IF_NONE",
                       "args": [
                         [  {  "prim": "PUSH",
                               "args": [
                                 {  "prim": "nat"  },
                                 {  "int": "0"  }
                               ]
                         }  ],
                         [  {  "prim": "DUP"  },
                         {  "prim": "CDR"  },
                         {  "prim": "DUP",
                            "args": [
                              {  "int": "7"  }
                            ]
                         },
                         {  "prim": "GET"  },
                         {  "prim": "IF_NONE",
                            "args": [
                              [  {  "prim": "PUSH",
                                    "args": [
                                      {  "prim": "nat"  },
                                      {  "int": "0"  }
                                    ]
                              }  ],
                              [    ]
                            ]
                         },
                         {  "prim": "SWAP"  },
                         {  "prim": "DROP",
                            "args": [
                              {  "int": "1"  }
                            ]
                         }  ]
                       ]
                    },
                    {  "prim": "TRANSFER_TOKENS"  },
                    {  "prim": "CONS"  },
                    {  "prim": "ITER",
                       "args": [
                         [  {  "prim": "CONS"  }  ]
                       ]
                    },
                    {  "prim": "DIP",
                       "args": [
                         {  "int": "1"  },
                         [  {  "prim": "DIG",
                               "args": [
                                 {  "int": "4"  }
                               ]
                         },
                         {  "prim": "DROP",
                            "args": [
                              {  "int": "1"  }
                            ]
                         }  ]
                       ]
                    },
                    {  "prim": "DUG",
                       "args": [
                         {  "int": "4"  }
                       ]
                    },
                    {  "prim": "DROP",
                       "args": [
                         {  "int": "3"  }
                       ]
                    },
                    {  "prim": "DIG",
                       "args": [
                         {  "int": "1"  }
                       ]
                    },
                    {  "prim": "PAIR"  }  ],
                    [  {  "prim": "UNPAIR"  },
                    {  "prim": "NIL",
                       "args": [
                         {  "prim": "operation"  }
                       ]
                    },
                    {  "prim": "NIL",
                       "args": [
                         {  "prim": "operation"  }
                       ]
                    },
                    {  "prim": "DUP",
                       "args": [
                         {  "int": "6"  }
                       ]
                    },
                    {  "prim": "ITER",
                       "args": [
                         [  {  "prim": "CONS"  }  ]
                       ]
                    },
                    {  "prim": "DUP",
                       "args": [
                         {  "int": "4"  }
                       ]
                    },
                    {  "prim": "AMOUNT"  },
                    {  "prim": "DUP",
                       "args": [
                         {  "int": "7"  }
                       ]
                    },
                    {  "prim": "DUP",
                       "args": [
                         {  "int": "6"  }
                       ]
                    },
                    {  "prim": "GET"  },
                    {  "prim": "IF_NONE",
                       "args": [
                         [  {  "prim": "PUSH",
                               "args": [
                                 {  "prim": "nat"  },
                                 {  "int": "0"  }
                               ]
                         }  ],
                         [  {  "prim": "DUP"  },
                         {  "prim": "CAR"  },
                         {  "prim": "SWAP"  },
                         {  "prim": "DROP",
                            "args": [
                              {  "int": "1"  }
                            ]
                         }  ]
                       ]
                    },
                    {  "prim": "TRANSFER_TOKENS"  },
                    {  "prim": "CONS"  },
                    {  "prim": "ITER",
                       "args": [
                         [  {  "prim": "CONS"  }  ]
                       ]
                    },
                    {  "prim": "DIP",
                       "args": [
                         {  "int": "1"  },
                         [  {  "prim": "DIG",
                               "args": [
                                 {  "int": "3"  }
                               ]
                         },
                         {  "prim": "DROP",
                            "args": [
                              {  "int": "1"  }
                            ]
                         }  ]
                       ]
                    },
                    {  "prim": "DUG",
                       "args": [
                         {  "int": "3"  }
                       ]
                    },
                    {  "prim": "DROP",
                       "args": [
                         {  "int": "2"  }
                       ]
                    },
                    {  "prim": "DIG",
                       "args": [
                         {  "int": "1"  }
                       ]
                    },
                    {  "prim": "PAIR"  }  ]
                  ]
            }  ],
            [  {  "prim": "IF_LEFT",
                  "args": [
                    [  {  "prim": "UNPAIR"  },
                    {  "prim": "SWAP"  },
                    {  "prim": "UNPAIR"  },
                    {  "prim": "SWAP"  },
                    {  "prim": "DUP"  },
                    {  "prim": "DUP",
                       "args": [
                         {  "int": "5"  }
                       ]
                    },
                    {  "prim": "DUP",
                       "args": [
                         {  "int": "5"  }
                       ]
                    },
                    {  "prim": "GET"  },
                    {  "prim": "IF_NONE",
                       "args": [
                         [  {  "prim": "PUSH",
                               "args": [
                                 {  "prim": "string"  },
                                 {  "string": "ledger"  }
                               ]
                         },
                         {  "prim": "PUSH",
                            "args": [
                              {  "prim": "string"  },
                              {  "string": "ASSET_NOT_FOUND"  }
                            ]
                         },
                         {  "prim": "PAIR"  },
                         {  "prim": "FAILWITH"  }  ],
                         [    ]
                       ]
                    },
                    {  "prim": "CAR"  },
                    {  "prim": "COMPARE"  },
                    {  "prim": "GE"  },
                    {  "prim": "NOT"  },
                    {  "prim": "IF",
                       "args": [
                         [  {  "prim": "PUSH",
                               "args": [
                                 {  "prim": "string"  },
                                 {  "string": "NotEnoughBalance"  }
                               ]
                         },
                         {  "prim": "FAILWITH"  }  ],
                         [    ]
                       ]
                    },
                    {  "prim": "DUP",
                       "args": [
                         {  "int": "3"  }
                       ]
                    },
                    {  "prim": "SENDER"  },
                    {  "prim": "COMPARE"  },
                    {  "prim": "NEQ"  },
                    {  "prim": "IF",
                       "args": [
                         [  {  "prim": "DUP",
                               "args": [
                                 {  "int": "4"  }
                               ]
                         },
                         {  "prim": "DUP",
                            "args": [
                              {  "int": "4"  }
                            ]
                         },
                         {  "prim": "GET"  },
                         {  "prim": "IF_NONE",
                            "args": [
                              [  {  "prim": "PUSH",
                                    "args": [
                                      {  "prim": "string"  },
                                      {  "string": "ledger"  }
                                    ]
                              },
                              {  "prim": "PUSH",
                                 "args": [
                                   {  "prim": "string"  },
                                   {  "string": "ASSET_NOT_FOUND"  }
                                 ]
                              },
                              {  "prim": "PAIR"  },
                              {  "prim": "FAILWITH"  }  ],
                              [    ]
                            ]
                         },
                         {  "prim": "CDR"  },
                         {  "prim": "SENDER"  },
                         {  "prim": "GET"  },
                         {  "prim": "IF_NONE",
                            "args": [
                              [  {  "prim": "PUSH",
                                    "args": [
                                      {  "prim": "nat"  },
                                      {  "int": "0"  }
                                    ]
                              }  ],
                              [    ]
                            ]
                         },
                         {  "prim": "DUP",
                            "args": [
                              {  "int": "2"  }
                            ]
                         },
                         {  "prim": "INT"  },
                         {  "prim": "DUP",
                            "args": [
                              {  "int": "2"  }
                            ]
                         },
                         {  "prim": "INT"  },
                         {  "prim": "SUB"  },
                         {  "prim": "ISNAT"  },
                         {  "prim": "IF_NONE",
                            "args": [
                              [  {  "prim": "DUP"  },
                              {  "prim": "DUP",
                                 "args": [
                                   {  "int": "3"  }
                                 ]
                              },
                              {  "prim": "PAIR"  },
                              {  "prim": "PUSH",
                                 "args": [
                                   {  "prim": "string"  },
                                   {  "string": "NotEnoughAllowance"  }
                                 ]
                              },
                              {  "prim": "PAIR"  },
                              {  "prim": "FAILWITH"  }  ],
                              [    ]
                            ]
                         },
                         {  "prim": "DUP",
                            "args": [
                              {  "int": "6"  }
                            ]
                         },
                         {  "prim": "DUP",
                            "args": [
                              {  "int": "7"  }
                            ]
                         },
                         {  "prim": "DUP",
                            "args": [
                              {  "int": "7"  }
                            ]
                         },
                         {  "prim": "GET"  },
                         {  "prim": "IF_NONE",
                            "args": [
                              [  {  "prim": "PUSH",
                                    "args": [
                                      {  "prim": "string"  },
                                      {  "string": "ledger"  }
                                    ]
                              },
                              {  "prim": "PUSH",
                                 "args": [
                                   {  "prim": "string"  },
                                   {  "string": "ASSET_NOT_FOUND"  }
                                 ]
                              },
                              {  "prim": "PAIR"  },
                              {  "prim": "FAILWITH"  }  ],
                              [    ]
                            ]
                         },
                         {  "prim": "UNPAIR"  },
                         {  "prim": "SWAP"  },
                         {  "prim": "DROP",
                            "args": [
                              {  "int": "1"  }
                            ]
                         },
                         {  "prim": "DUP",
                            "args": [
                              {  "int": "8"  }
                            ]
                         },
                         {  "prim": "DUP",
                            "args": [
                              {  "int": "8"  }
                            ]
                         },
                         {  "prim": "GET"  },
                         {  "prim": "IF_NONE",
                            "args": [
                              [  {  "prim": "PUSH",
                                    "args": [
                                      {  "prim": "string"  },
                                      {  "string": "ledger"  }
                                    ]
                              },
                              {  "prim": "PUSH",
                                 "args": [
                                   {  "prim": "string"  },
                                   {  "string": "ASSET_NOT_FOUND"  }
                                 ]
                              },
                              {  "prim": "PAIR"  },
                              {  "prim": "FAILWITH"  }  ],
                              [    ]
                            ]
                         },
                         {  "prim": "CDR"  },
                         {  "prim": "DUP",
                            "args": [
                              {  "int": "4"  }
                            ]
                         },
                         {  "prim": "SOME"  },
                         {  "prim": "SENDER"  },
                         {  "prim": "UPDATE"  },
                         {  "prim": "SWAP"  },
                         {  "prim": "PAIR"  },
                         {  "prim": "SOME"  },
                         {  "prim": "DUP",
                            "args": [
                              {  "int": "7"  }
                            ]
                         },
                         {  "prim": "UPDATE"  },
                         {  "prim": "DIP",
                            "args": [
                              {  "int": "1"  },
                              [  {  "prim": "DIG",
                                    "args": [
                                      {  "int": "5"  }
                                    ]
                              },
                              {  "prim": "DROP",
                                 "args": [
                                   {  "int": "1"  }
                                 ]
                              }  ]
                            ]
                         },
                         {  "prim": "DUG",
                            "args": [
                              {  "int": "5"  }
                            ]
                         },
                         {  "prim": "DROP",
                            "args": [
                              {  "int": "2"  }
                            ]
                         }  ],
                         [    ]
                       ]
                    },
                    {  "prim": "DUP",
                       "args": [
                         {  "int": "4"  }
                       ]
                    },
                    {  "prim": "DUP",
                       "args": [
                         {  "int": "4"  }
                       ]
                    },
                    {  "prim": "GET"  },
                    {  "prim": "IF_NONE",
                       "args": [
                         [  {  "prim": "PUSH",
                               "args": [
                                 {  "prim": "string"  },
                                 {  "string": "ledger"  }
                               ]
                         },
                         {  "prim": "PUSH",
                            "args": [
                              {  "prim": "string"  },
                              {  "string": "ASSET_NOT_FOUND"  }
                            ]
                         },
                         {  "prim": "PAIR"  },
                         {  "prim": "FAILWITH"  }  ],
                         [    ]
                       ]
                    },
                    {  "prim": "DUP",
                       "args": [
                         {  "int": "5"  }
                       ]
                    },
                    {  "prim": "DUP",
                       "args": [
                         {  "int": "6"  }
                       ]
                    },
                    {  "prim": "DUP",
                       "args": [
                         {  "int": "6"  }
                       ]
                    },
                    {  "prim": "GET"  },
                    {  "prim": "IF_NONE",
                       "args": [
                         [  {  "prim": "PUSH",
                               "args": [
                                 {  "prim": "string"  },
                                 {  "string": "ledger"  }
                               ]
                         },
                         {  "prim": "PUSH",
                            "args": [
                              {  "prim": "string"  },
                              {  "string": "ASSET_NOT_FOUND"  }
                            ]
                         },
                         {  "prim": "PAIR"  },
                         {  "prim": "FAILWITH"  }  ],
                         [    ]
                       ]
                    },
                    {  "prim": "UNPAIR"  },
                    {  "prim": "DROP",
                       "args": [
                         {  "int": "1"  }
                       ]
                    },
                    {  "prim": "PUSH",
                       "args": [
                         {  "prim": "int"  },
                         {  "int": "0"  }
                       ]
                    },
                    {  "prim": "DUP",
                       "args": [
                         {  "int": "5"  }
                       ]
                    },
                    {  "prim": "INT"  },
                    {  "prim": "DUP",
                       "args": [
                         {  "int": "5"  }
                       ]
                    },
                    {  "prim": "CAR"  },
                    {  "prim": "SUB"  },
                    {  "prim": "COMPARE"  },
                    {  "prim": "GE"  },
                    {  "prim": "IF",
                       "args": [
                         [  {  "prim": "DUP",
                               "args": [
                                 {  "int": "4"  }
                               ]
                         },
                         {  "prim": "INT"  },
                         {  "prim": "DUP",
                            "args": [
                              {  "int": "4"  }
                            ]
                         },
                         {  "prim": "CAR"  },
                         {  "prim": "SUB"  },
                         {  "prim": "ABS"  }  ],
                         [  {  "prim": "PUSH",
                               "args": [
                                 {  "prim": "string"  },
                                 {  "string": "NAT_NEG_ASSIGN"  }
                               ]
                         },
                         {  "prim": "FAILWITH"  }  ]
                       ]
                    },
                    {  "prim": "PAIR"  },
                    {  "prim": "SOME"  },
                    {  "prim": "DUP",
                       "args": [
                         {  "int": "6"  }
                       ]
                    },
                    {  "prim": "UPDATE"  },
                    {  "prim": "DIP",
                       "args": [
                         {  "int": "1"  },
                         [  {  "prim": "DIG",
                               "args": [
                                 {  "int": "4"  }
                               ]
                         },
                         {  "prim": "DROP",
                            "args": [
                              {  "int": "1"  }
                            ]
                         }  ]
                       ]
                    },
                    {  "prim": "DUG",
                       "args": [
                         {  "int": "4"  }
                       ]
                    },
                    {  "prim": "DROP",
                       "args": [
                         {  "int": "1"  }
                       ]
                    },
                    {  "prim": "DUP",
                       "args": [
                         {  "int": "4"  }
                       ]
                    },
                    {  "prim": "DUP",
                       "args": [
                         {  "int": "3"  }
                       ]
                    },
                    {  "prim": "MEM"  },
                    {  "prim": "IF",
                       "args": [
                         [  {  "prim": "DUP",
                               "args": [
                                 {  "int": "4"  }
                               ]
                         },
                         {  "prim": "DUP",
                            "args": [
                              {  "int": "3"  }
                            ]
                         },
                         {  "prim": "GET"  },
                         {  "prim": "IF_NONE",
                            "args": [
                              [  {  "prim": "PUSH",
                                    "args": [
                                      {  "prim": "string"  },
                                      {  "string": "ledger"  }
                                    ]
                              },
                              {  "prim": "PUSH",
                                 "args": [
                                   {  "prim": "string"  },
                                   {  "string": "ASSET_NOT_FOUND"  }
                                 ]
                              },
                              {  "prim": "PAIR"  },
                              {  "prim": "FAILWITH"  }  ],
                              [    ]
                            ]
                         },
                         {  "prim": "DUP",
                            "args": [
                              {  "int": "5"  }
                            ]
                         },
                         {  "prim": "DUP",
                            "args": [
                              {  "int": "6"  }
                            ]
                         },
                         {  "prim": "DUP",
                            "args": [
                              {  "int": "5"  }
                            ]
                         },
                         {  "prim": "GET"  },
                         {  "prim": "IF_NONE",
                            "args": [
                              [  {  "prim": "PUSH",
                                    "args": [
                                      {  "prim": "string"  },
                                      {  "string": "ledger"  }
                                    ]
                              },
                              {  "prim": "PUSH",
                                 "args": [
                                   {  "prim": "string"  },
                                   {  "string": "ASSET_NOT_FOUND"  }
                                 ]
                              },
                              {  "prim": "PAIR"  },
                              {  "prim": "FAILWITH"  }  ],
                              [    ]
                            ]
                         },
                         {  "prim": "UNPAIR"  },
                         {  "prim": "DROP",
                            "args": [
                              {  "int": "1"  }
                            ]
                         },
                         {  "prim": "DUP",
                            "args": [
                              {  "int": "4"  }
                            ]
                         },
                         {  "prim": "DUP",
                            "args": [
                              {  "int": "4"  }
                            ]
                         },
                         {  "prim": "CAR"  },
                         {  "prim": "ADD"  },
                         {  "prim": "PAIR"  },
                         {  "prim": "SOME"  },
                         {  "prim": "DUP",
                            "args": [
                              {  "int": "5"  }
                            ]
                         },
                         {  "prim": "UPDATE"  },
                         {  "prim": "DIP",
                            "args": [
                              {  "int": "1"  },
                              [  {  "prim": "DIG",
                                    "args": [
                                      {  "int": "4"  }
                                    ]
                              },
                              {  "prim": "DROP",
                                 "args": [
                                   {  "int": "1"  }
                                 ]
                              }  ]
                            ]
                         },
                         {  "prim": "DUG",
                            "args": [
                              {  "int": "4"  }
                            ]
                         },
                         {  "prim": "DROP",
                            "args": [
                              {  "int": "1"  }
                            ]
                         }  ],
                         [  {  "prim": "DUP",
                               "args": [
                                 {  "int": "4"  }
                               ]
                         },
                         {  "prim": "EMPTY_MAP",
                            "args": [
                              {  "prim": "address"  },
                              {  "prim": "nat"  }
                            ]
                         },
                         {  "prim": "DUP",
                            "args": [
                              {  "int": "3"  }
                            ]
                         },
                         {  "prim": "PUSH",
                            "args": [
                              {  "prim": "nat"  },
                              {  "int": "0"  }
                            ]
                         },
                         {  "prim": "ADD"  },
                         {  "prim": "PAIR"  },
                         {  "prim": "SOME"  },
                         {  "prim": "DUP",
                            "args": [
                              {  "int": "4"  }
                            ]
                         },
                         {  "prim": "UPDATE"  },
                         {  "prim": "DIP",
                            "args": [
                              {  "int": "1"  },
                              [  {  "prim": "DIG",
                                    "args": [
                                      {  "int": "3"  }
                                    ]
                              },
                              {  "prim": "DROP",
                                 "args": [
                                   {  "int": "1"  }
                                 ]
                              }  ]
                            ]
                         },
                         {  "prim": "DUG",
                            "args": [
                              {  "int": "3"  }
                            ]
                         }  ]
                       ]
                    },
                    {  "prim": "DROP",
                       "args": [
                         {  "int": "3"  }
                       ]
                    },
                    {  "prim": "DIG",
                       "args": [
                         {  "int": "1"  }
                       ]
                    },
                    {  "prim": "PAIR"  }  ],
                    [  {  "prim": "UNPAIR"  },
                    {  "prim": "SWAP"  },
                    {  "prim": "DUP",
                       "args": [
                         {  "int": "3"  }
                       ]
                    },
                    {  "prim": "SENDER"  },
                    {  "prim": "GET"  },
                    {  "prim": "IF_NONE",
                       "args": [
                         [  {  "prim": "PUSH",
                               "args": [
                                 {  "prim": "nat"  },
                                 {  "int": "0"  }
                               ]
                         }  ],
                         [  {  "prim": "DUP"  },
                         {  "prim": "CDR"  },
                         {  "prim": "DUP",
                            "args": [
                              {  "int": "4"  }
                            ]
                         },
                         {  "prim": "GET"  },
                         {  "prim": "IF_NONE",
                            "args": [
                              [  {  "prim": "PUSH",
                                    "args": [
                                      {  "prim": "nat"  },
                                      {  "int": "0"  }
                                    ]
                              }  ],
                              [    ]
                            ]
                         },
                         {  "prim": "SWAP"  },
                         {  "prim": "DROP",
                            "args": [
                              {  "int": "1"  }
                            ]
                         }  ]
                       ]
                    },
                    {  "prim": "PUSH",
                       "args": [
                         {  "prim": "nat"  },
                         {  "int": "0"  }
                       ]
                    },
                    {  "prim": "DUP",
                       "args": [
                         {  "int": "2"  }
                       ]
                    },
                    {  "prim": "COMPARE"  },
                    {  "prim": "GT"  },
                    {  "prim": "IF",
                       "args": [
                         [  {  "prim": "PUSH",
                               "args": [
                                 {  "prim": "nat"  },
                                 {  "int": "0"  }
                               ]
                         },
                         {  "prim": "DUP",
                            "args": [
                              {  "int": "3"  }
                            ]
                         },
                         {  "prim": "COMPARE"  },
                         {  "prim": "GT"  },
                         {  "prim": "IF",
                            "args": [
                              [  {  "prim": "PUSH",
                                    "args": [
                                      {  "prim": "bool"  },
                                      {  "prim": "True"  }
                                    ]
                              }  ],
                              [  {  "prim": "PUSH",
                                    "args": [
                                      {  "prim": "bool"  },
                                      {  "prim": "False"  }
                                    ]
                              }  ]
                            ]
                         }  ],
                         [  {  "prim": "PUSH",
                               "args": [
                                 {  "prim": "bool"  },
                                 {  "prim": "False"  }
                               ]
                         }  ]
                       ]
                    },
                    {  "prim": "IF",
                       "args": [
                         [  {  "prim": "DUP"  },
                         {  "prim": "PUSH",
                            "args": [
                              {  "prim": "string"  },
                              {  "string": "UnsafeAllowanceChange"  }
                            ]
                         },
                         {  "prim": "PAIR"  },
                         {  "prim": "FAILWITH"  }  ],
                         [    ]
                       ]
                    },
                    {  "prim": "DUP",
                       "args": [
                         {  "int": "4"  }
                       ]
                    },
                    {  "prim": "SENDER"  },
                    {  "prim": "MEM"  },
                    {  "prim": "IF",
                       "args": [
                         [  {  "prim": "DUP",
                               "args": [
                                 {  "int": "4"  }
                               ]
                         },
                         {  "prim": "DUP",
                            "args": [
                              {  "int": "5"  }
                            ]
                         },
                         {  "prim": "SENDER"  },
                         {  "prim": "GET"  },
                         {  "prim": "IF_NONE",
                            "args": [
                              [  {  "prim": "PUSH",
                                    "args": [
                                      {  "prim": "string"  },
                                      {  "string": "ledger"  }
                                    ]
                              },
                              {  "prim": "PUSH",
                                 "args": [
                                   {  "prim": "string"  },
                                   {  "string": "ASSET_NOT_FOUND"  }
                                 ]
                              },
                              {  "prim": "PAIR"  },
                              {  "prim": "FAILWITH"  }  ],
                              [    ]
                            ]
                         },
                         {  "prim": "UNPAIR"  },
                         {  "prim": "SWAP"  },
                         {  "prim": "DROP",
                            "args": [
                              {  "int": "1"  }
                            ]
                         },
                         {  "prim": "DUP",
                            "args": [
                              {  "int": "6"  }
                            ]
                         },
                         {  "prim": "SENDER"  },
                         {  "prim": "GET"  },
                         {  "prim": "IF_NONE",
                            "args": [
                              [  {  "prim": "PUSH",
                                    "args": [
                                      {  "prim": "string"  },
                                      {  "string": "ledger"  }
                                    ]
                              },
                              {  "prim": "PUSH",
                                 "args": [
                                   {  "prim": "string"  },
                                   {  "string": "ASSET_NOT_FOUND"  }
                                 ]
                              },
                              {  "prim": "PAIR"  },
                              {  "prim": "FAILWITH"  }  ],
                              [    ]
                            ]
                         },
                         {  "prim": "CDR"  },
                         {  "prim": "DUP",
                            "args": [
                              {  "int": "5"  }
                            ]
                         },
                         {  "prim": "SOME"  },
                         {  "prim": "DUP",
                            "args": [
                              {  "int": "7"  }
                            ]
                         },
                         {  "prim": "UPDATE"  },
                         {  "prim": "SWAP"  },
                         {  "prim": "PAIR"  },
                         {  "prim": "SOME"  },
                         {  "prim": "SENDER"  },
                         {  "prim": "UPDATE"  },
                         {  "prim": "DIP",
                            "args": [
                              {  "int": "1"  },
                              [  {  "prim": "DIG",
                                    "args": [
                                      {  "int": "3"  }
                                    ]
                              },
                              {  "prim": "DROP",
                                 "args": [
                                   {  "int": "1"  }
                                 ]
                              }  ]
                            ]
                         },
                         {  "prim": "DUG",
                            "args": [
                              {  "int": "3"  }
                            ]
                         }  ],
                         [  {  "prim": "DUP",
                               "args": [
                                 {  "int": "4"  }
                               ]
                         },
                         {  "prim": "EMPTY_MAP",
                            "args": [
                              {  "prim": "address"  },
                              {  "prim": "nat"  }
                            ]
                         },
                         {  "prim": "DUP",
                            "args": [
                              {  "int": "4"  }
                            ]
                         },
                         {  "prim": "SOME"  },
                         {  "prim": "DUP",
                            "args": [
                              {  "int": "6"  }
                            ]
                         },
                         {  "prim": "UPDATE"  },
                         {  "prim": "PUSH",
                            "args": [
                              {  "prim": "nat"  },
                              {  "int": "0"  }
                            ]
                         },
                         {  "prim": "PAIR"  },
                         {  "prim": "SOME"  },
                         {  "prim": "SENDER"  },
                         {  "prim": "UPDATE"  },
                         {  "prim": "DIP",
                            "args": [
                              {  "int": "1"  },
                              [  {  "prim": "DIG",
                                    "args": [
                                      {  "int": "3"  }
                                    ]
                              },
                              {  "prim": "DROP",
                                 "args": [
                                   {  "int": "1"  }
                                 ]
                              }  ]
                            ]
                         },
                         {  "prim": "DUG",
                            "args": [
                              {  "int": "3"  }
                            ]
                         }  ]
                       ]
                    },
                    {  "prim": "DROP",
                       "args": [
                         {  "int": "3"  }
                       ]
                    },
                    {  "prim": "DIG",
                       "args": [
                         {  "int": "1"  }
                       ]
                    },
                    {  "prim": "PAIR"  }  ]
                  ]
            }  ]
          ]
       }  ]
     ]
  }  ];

export const getStorage = (initial_holder, total_supply) => {
  return [  {  "prim": "Elt",
               "args": [
                 {  "string": initial_holder  },
                 {  "prim": "Pair",
                    "args": [
                      {"int": total_supply.toString()},
                      [    ]
                    ]
                 }
               ]
         }  ];
  }
